### PR TITLE
feat: dev shell to easy build and run e2e

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
`nix develop` enters shell which can do all make and e2e and protogen, without anything installed beforehand

### CODE REVIEW

**Comment by dzmitry-lahoda** [comment]
@bluele may you consider merging this to avoid me dragging over commits? so i can do IBC Hooks PRs without additional files for nix in PR

**Comment by bluele** [comment]
Hi @dzmitry-lahoda,  thanks for your PR.

Sorry, I have no experience of nix and don't have enough time to check this, so I can't decide if it makes sense to adopt and continue maintaining this for now.  Does this make it easier to integrate with other repositories? If so, please tell us some use cases.

Seems that this is helpful for setting up a development environment, so I don't think it would affect other PR like feature development without merging this immediately, but do I misunderstand something?

**Comment by dzmitry-lahoda** [comment]
scenario, dev on linux(mac too) with docker and nix(generic package manager, now brew or apk), clone the repo. runs nix develop.
and he is 100% ready to run and test and proto gen whole this repo guaranted. 

while current say to clone some other repo, install forge, pip, python, go, solc, npm, some plugins, protobuf of versions which work.

for me inability to shell of repo given i do dozens of blockchian repos with its own rules and versions of operating is work stoppage.

**Comment by dzmitry-lahoda** [comment]
I use nix for Polkadot https://github.com/paritytech/zombienet/blob/main/flake-module.nix

**Comment by dzmitry-lahoda** [comment]
ether also has official nix support https://github.com/nix-community/ethereum.nix

**Comment by dzmitry-lahoda** [comment]
https://github.com/andresilva/nix-polkadot

https://github.com/informalsystems/cosmos.nix

so nix just allows to glue e2e cross chain flows and wiled builds.

**Comment by dzmitry-lahoda** [comment]
@bluele you no need to maintain that. nix people maintain it when they glue and send prs.

**Comment by dzmitry-lahoda** [comment]
here is example how ibc-rs uses this for testing some support of CosmWasm contracts in CI https://github.com/cosmos/ibc-rs/blob/fa07561d04fb8d850625c7574c07c6921e3cf13a/.github/workflows/cw-check.yaml#L33

for example.

**Comment by dzmitry-lahoda** [comment]
@bluele what do you think?

it will allow any devs way more easy to contiribute, verify and use this repo in their own CI. 

i know it will take a little bit extra expertise of you and give it for free to other people, but same time it will drive IBC adoption around.

**Pull request closed without merging**
