### PR TITLE
feat: ics30 interfaces

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
for https://github.com/hyperledger-labs/yui-ibc-solidity/issues/184

I need this + your work on memo to have work on ibc hooks eth version

### CODE REVIEW

**Comment by bluele** [comment]
OK, I will consider it. Please wait for a while.

**Comment by dzmitry-lahoda** [comment]
we have private repo were people do clever things, so i can contribute to both my applicaiton level stuff. specifically Osmosis IBC Hooks analog to call `eth` contract via MEMO. I need decision on collaboration and middleware.

**Comment by dzmitry-lahoda** [comment]
as we will be private next 3 month, i would like not to diverge codes to far further

**Comment by bluele** [comment]
@dzmitry-lahoda I have show an example for middleware design pattern at https://github.com/hyperledger-labs/yui-ibc-solidity/issues/184#issuecomment-1772372816. What do you think about this?

**Pull request closed without merging**
